services:
  elasticsearch:
    build:
      context: .
      dockerfile: docker/Dockerfile.elasticsearch
    container_name: elasticsearch_dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: elasticsearch_api
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8000:8000"